import { Inter } from "next/font/google";
import "./globals.css";
import TopBar from "@/layout/TopBar/TopBar";
import Footer from "@/layout/Footer/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Portifolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TopBar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
